<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.Playwright" Version="1.60.0" />
    <PackageReference Include="AngleSharp" Version="1.5.2" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="PDFtoImage" Version="5.3.0" />
  </ItemGroup>
</Project>
